### ISSUE TITLE
Unresolved identifier 'XCTWaiter'

### ISSUE THREAD

**Issue by lferro9000** [Shashikant86/XCFit#10]
When generating a test project with XCFit, after installing the pods i get in the Podfile.lock:
```
PODS:
  - Cucumberish (1.1.0)
  - XCFit (4.0.0):
    - Cucumberish

DEPENDENCIES:
  - XCFit

SPEC CHECKSUMS:
  Cucumberish: d56601ffdabf0cf3ee2f6cce13db90430ff2c8f7
  XCFit: cb643d570a3f4588cab3761d282e82e293c8dc2c

PODFILE CHECKSUM: 1ff7977e2cf9463b9b9a7311b73708d886264b11

COCOAPODS: 1.2.0
```
Then, i updated the testbase class by removing the comment and extent if from XCFit.

Then moved to HomeScreenTest.swift, uncommented the:

```
givenILaunchedApplication()
```
And run the test.

The expected result would be to run the app in simulator, run the test and pass (maybe with warnings as there is no expectations).

The actual result was 4 errors:
```
21:       let result = XCTWaiter().wait(for: [xcfitExpectation], timeout: 60)
30:       let result = XCTWaiter().wait(for: [xcfitExpectation], timeout: 60)
38:       let result = XCTWaiter().wait(for: [xcfitExpectation], timeout: 60)
46:       let result = XCTWaiter().wait(for: [xcfitExpectation], timeout: 60)
```
All with the error of: Use of unresolved identifier 'XCTWaiter'.

**Comment by Shashikant86** [comment]
@lferro9000 Yeah.. thats my bad.. latest version of the Pod has the Swift 3.1 features like XCWaiter and XCUiSiriService. Can you please point your Pod to 3.0.0 version or Swift 3.0.2 branch please 

`pod 'XCFit', :git => 'https://github.com/Shashikant86/XCFit.git', :branch => 'Swift3.0.2'`

This will definitely work :) Let me know if you still have issues

**Comment by Shashikant86** [comment]
@lferro9000 You can also point Pod to `3.0.0` tag and it should work as well 

` pod 'XCFit', :git => 'https://github.com/Shashikant86/XCFit.git', :tag => '3.1.1'`
