### ISSUE TITLE
How can i convert junit.xml generated using xcpretty after the test run to a pretty cucumber report as in cucumber-reporting plugin for java

### ISSUE THREAD

**Issue by pawankums** [Shashikant86/XCFit#13]

**Comment by Shashikant86** [comment]
XCPrerry has few formatters like `rspec` , `tap` and `knock` .. Refer xcpretty README[ here](https://github.com/supermarin/xcpretty#formats)

**Comment by Shashikant86** [comment]
On other note, its related to xcfit at all ..
