### ISSUE TITLE
Found error when setup template for xcode 8

### ISSUE THREAD

**Issue by fedika** [Shashikant86/XCFit#7]
Hi,
I've tried to use command `xcfit setup_xcode_templates`

But the result is

> Welcome to XCFit: Full Stack BDD framework for iOS app
> ==================XXXXXXXX===========================
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1375:in `copy': unknown file type: /usr/local/bin/../XCFit_Templates/XCFit (RuntimeError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `call'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `wrap_traverse'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
> 	from /usr/local/bin/xcfit:26:in `setup_xcode_templates'
> 	from /usr/local/bin/xcfit:142:in `<main>'

**Comment by Shashikant86** [comment]
Thanks for reporting. Please use rubygem version for now than home brew I will fix it asap

**Comment by Shashikant86** [comment]
@fergadipa This issue should be fixed now. Please uninstall existing homebrew and install xcfit 

                               $ brew uninstall xcfit 
                               $ brew install xcfit 

Hope this will fix it :) Let me know

**Comment by fedika** [comment]
Awesome!
It works :)

**Comment by JustaLab** [comment]
Hey,
I've tried to install the package throught homebrew but i'm getting:
```Error: No available formula with the name "xcfit"```

Also I'm getting the same error after installing with ruby

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcfit-7.0.0/bin/xcfit:3:in `<top (required)>'
	from /usr/local/bin/xcfit:22:in `load'
	from /usr/local/bin/xcfit:22:in `<main>'
Emiliens-MacBook-Pro:Her-iOS Emilien$ xcfit
```
