### ISSUE TITLE
 Showing Recent Issues clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by fedika** [Shashikant86/XCFit#8]
Hi again Shashikant,

So I am excited and want to test the ios mobile app from https://github.com/testmunk/TMSample.git using XCFit.
The app works fine.
Then I followed every your steps until warning and error come when Build for Testing.
The warning is 

> /Users/fergadipa/Documents/Workspace/TMSample/TMSample/TestmunkDemoCucumberTests/TestmunkDemoCucumberTests.swift:35:21: 'executeFeatures(inDirectory:includeTags:excludeTags:)' is deprecated: This method is deprecated because it can cause issues if you installed Cucumberish using Cocoapods. Instead use the method executeFeaturesInDirectory:fromBundle:includeTags:(NSArray *)tags excludeTags:

And the error is

> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please kindly suggestion how to solve the error :)

**Comment by Shashikant86** [comment]
@fergadipa Happy to help ! ... Which version of Swift and Xcode you are using at the moment.. It looks ok to me here ..

**Comment by Shashikant86** [comment]
@fergadipa I can see the warning but no error ... Let me know how you downloaded cucumbers? 

I would recommend manual download .. it worked for me ...

**Comment by fedika** [comment]
great!
I tried manual download Cucumber and it works, thank you :)
